### PR TITLE
Support subdomains added as domains in CP

### PR DESCRIPTION
**Pull request by Lillecarl**
This'll allow us to have add certs when we have subdomains delegated to GleSYS and added in control panel.

For example:
subdomain.domain.com wouldn't work, it'd fail because of domain splitting.

This also solves not being able to work with co.uk domains and such :)

### CODE REVIEW

**Comment by Lillecarl** [comment]
This approach should be applicable on certbot-loopia too.

**Comment by Lillecarl** [comment]
@runfalk Thoughts? :)

**Comment by runfalk** [comment]
Hi @Lillecarl,

Sorry for the delay, I saw your PR on my phone and then kind of forgot about it. In certbot-loopia I implemented proper domain splitting this way https://github.com/runfalk/loopialib/blob/master/loopialib/utils.py (loopialib is a dependency). Because of how Loopia's control panel works it won't have the same problem, I think.

Though I dislike the brute forcing aspect I can't think of a more robust solution.

Thank you for the contribution!

**Comment by Lillecarl** [comment]
I agree that it's a bit dirty, but as you say there's no more robust way of doing it that i can think of. This will also support any potential new TLD popping up.

https://github.com/certbot/certbot/blob/master/certbot-dns-digitalocean/certbot_dns_digitalocean/dns_digitalocean.py#L150
https://github.com/certbot/certbot/blob/master/certbot/plugins/dns_common.py#L319

Looking at the references i've linked here it seems like the official certbot implementations also brute-forces their way through the possible domains (with more Python ninja skills then i'm able to comprehend really)

See https://ideone.com/ORwzT9 for output of the certbot official impl.

Thanks for the merge, hope to see a PyPi release soon too! 😄

**Comment by runfalk** [comment]
I'll do some cleaning of your PR and then I'll release it. Hopefully later today :smile:

**Comment by runfalk** [comment]
I've released a version 0.2.0. Please test it and see if it works for you.

**Pull request merged**
